### ISSUE TITLE
how to install dependencies?

### ISSUE THREAD

**Issue by psteinb** [xaratustrah/decaydent#1]
it would be great to have a `requirements.txt` or `conda.yml` next to the code. Looking at the code, something like this might be enough at this moment (attention, this is untested):

```
$ cat requirement.txt
h5py
numpy
matplotlib
pillow
$ python -m venv --upgrade-deps myenv
$ source myenv/bin/activate
$ python -m pip install -r requirements.txt
```

**Comment by xaratustrah** [comment]
done
